image: node:latest

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  only:
    - main

build_project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - main

deploy_to_firebase:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - firebase deploy --only hosting,firestore --token $FIREBASE_TOKEN
  only:
    - main