name: Firebase CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Build (if needed)
        run: npm run build --if-present
      
      - name: Deploy to Firebase
        run: firebase deploy --only hosting,firestore --token ${{ secrets.FIREBASE_TOKEN }}